config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :calendar_sync_definitions do
    member do
      post :perform_sync
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar_id_map.rb
# == Schema Information
#
# Table name: calendar_id_maps
#
#  id                          :bigint           not null, primary key
#  google_cal_updated_at       :datetime
#  ics_uid                     :string
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  calendar_sync_definition_id :bigint
#  google_cal_id               :string
#
# Indexes
#
#  index_calendar_id_maps_on_calendar_sync_definition_id  (calendar_sync_definition_id)
#
class CalendarIdMap < ApplicationRecord
  belongs_to :calendar_sync_definition
end

app/models/calendar_sync_definition.rb
class CalendarSyncDefinition < ApplicationRecord
  belongs_to :user
  has_many :calendar_id_maps
end

# == Schema Information
#
# Table name: calendar_sync_definitions
#
#  id                         :bigint           not null, primary key
#  description_prepend_string :string
#  subscribed_calendar_url    :string
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  user_id                    :bigint
#
# Indexes
#
#  index_calendar_sync_definitions_on_user_id  (user_id)
#

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  expires                :string
#  expires_at             :string
#  google_auth            :jsonb
#  provider               :string
#  refresh_token          :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  token                  :string
#  uid                    :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_many :calendar_sync_definitions
  has_many :calendar_id_maps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :omniauthable,
         :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID

    user = where(provider: auth.provider, uid: auth.uid).first_or_create
    user.update!(
      email: auth.info.email,
      token: auth.credentials.token,
      expires: auth.credentials.expires,
      expires_at: auth.credentials.expires_at,
      refresh_token: auth.credentials.refresh_token,
      google_auth: auth,
    )
    user
  end

  def name
    google_auth.dig('info', 'name')
  end

  def email
    google_auth.dig('info', 'email')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

  def new_session_path(scope)
    new_user_session_path
  end

end

app/controllers/calendar_sync_definitions_controller.rb
class CalendarSyncDefinitionsController < ApplicationController

  def index
    @calendar_sync_definitions = current_user.calendar_sync_definitions
    if @calendar_sync_definitions.empty?
      redirect_to new_calendar_sync_definition_path
    end
  end

  def new
    @calendar_sync_definition = CalendarSyncDefinition.new(user: current_user)
  end

  def edit
    @calendar_sync_definition = current_user.calendar_sync_definitions.find(params[:id])
  end

  def create
    url = params[:calendar_sync_definition][:subscribed_calendar_url]
    current_user.calendar_sync_definitions.create!(subscribed_calendar_url: url)

    flash[:notice] = "sync definition created!"
    redirect_to calendar_sync_definitions_path
  end

  def update
    @calendar_sync_definition = current_user.calendar_sync_definitions.find(params[:id])

    @calendar_sync_definition.update!(calendar_sync_definition_params)
    flash[:notice] = "sync definition updated!"
    redirect_to calendar_sync_definitions_path
  end

  def perform_sync
    calendar_sync_definition = current_user.calendar_sync_definitions.find(params[:id])
    CalendarSyncJob.perform_later(calendar_sync_definition.id)

    flash[:notice] = "running sync"
    redirect_to calendar_sync_definitions_path
  end

  def calendar_sync_definition_params
    params.require(:calendar_sync_definition).permit(
      :subscribed_calendar_url,
      :description_prepend_string,
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controllers.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    Rails.logger.info { "*************** google_oauth2 Callback" }
    # Rails.logger.info { "request.env['omniauth.auth']: #{request.env["omniauth.auth"]}" } # security issue

    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
    end
    redirect_to '/'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendar_sync_definitions/_form.html.erb
<%= simple_form_for(@calendar_sync_definition) do |f| %>
  id: <%= @calendar_sync_definition.id %>
  <%= f.input :subscribed_calendar_url %>
  <%= f.input :description_prepend_string, hint: "This will be added at the top of the description on each event." %>
  <%= f.submit %>
<% end %>

app/views/calendar_sync_definitions/edit.html.erb
<%= render 'form' %>

app/views/calendar_sync_definitions/index.html.erb
<ul>
<% @calendar_sync_definitions.find_each do |calendar_sync_definition| %>
  <li>
    subscribed_calendar_url: <%= calendar_sync_definition.subscribed_calendar_url %><br>
    description_prepend_string: <%= calendar_sync_definition.description_prepend_string %>
    <%= button_to perform_sync_calendar_sync_definition_path(calendar_sync_definition), perform_sync_calendar_sync_definition_path(calendar_sync_definition) %>
    <%= link_to 'edit', edit_calendar_sync_definition_path(calendar_sync_definition) %>
  </li>
<% end %>
</ul>

app/views/calendar_sync_definitions/new.html.erb
<p>
  try these - <%= link_to "http://icalshare.com/", "http://icalshare.com/" %>
</p>
<%= render 'form' %>

app/views/home/index.html.erb
<p>
  hello World
</p>

<% if !current_user %>
  <%= button_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
<% end %>

<% if current_user %>
  <p>congrats, google sign in worked.</p>
  <ul>
    <li>
      <%= link_to calendar_sync_definitions_path, calendar_sync_definitions_path %>
    </li>
    <li>
      <%= link_to new_calendar_sync_definition_path, new_calendar_sync_definition_path %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarSubscriptionSync</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
  <%# if Rails.env.development? %>
    <h1><%= controller_name %>#<%= action_name %></h1>
    <h1>
      <% if current_user %>
        current_user: <%= "#{current_user&.id} #{current_user&.email}" %>
      <% else %>
        not signed in
      <% end %>
    </h1>
  <%# end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>